Сделал кликабельным лого
KirKol94/crm pull request #141
Opened 2024-02-14 12:54 UTC by nikita-osipov59

2024-02-14 12:59 UTC, KirKol94 requested changes

2024-02-14 12:59 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +          </Link>
А нахрен тут 2 линка ведущих на один урл?)

2024-02-14 13:04 UTC, nikita-osipov59 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +          </Link>
А как тогда?

2024-02-14 15:43 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +          </Link>
Ну ссылка то ведь у тебя одна, только содержимое меняется

2024-02-14 15:54 UTC, Devergence commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +          </Link>
<Link to={ROUTER_PATH.HOME}>
      isOpen  ? <Logo /> : <LogoMini />
 </Link>
 Почему не так?

2024-02-14 16:14 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +          </Link>
> Внутри линка сделай условие отображения логотипа

ну вот, избавил человека от небольшой мозговой деятельности)

2024-02-15 06:19 UTC, nikita-osipov59 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +          </Link>
Аа понял!

2024-02-15 09:41 UTC, KirKol94 approved these changes

2024-02-15 20:11 UTC, KirKol94 approved these changes

2024-02-15 20:12 UTC, merged