Сверстал Sidebar
KirKol94/crm pull request #32
Opened 2024-01-25 15:48 UTC by PavelHiga

- [x]  Добавил Layout + вложенный роутинг
- [x]  Сверстал Sidebar
- [x]  При нажатии на элемент внутри Sidebar меняется цвет активного элемента + срабатывает переадресация.
- [x]  Добавил возможно использовать BEM нейминг (сделан без плагинов, хз правильно ли это, но вроде работает :D )
- [x]  Сверстал палочку активного элемента в Sidebar
- [x]  Теперь Sidebar может открываться и закрываться
- [x]  Перенес Layout

![image](https://github.com/KirKol94/crm/assets/79961306/292f482d-0512-4b15-bd9f-8acdd79d0220)
![image](https://github.com/KirKol94/crm/assets/79961306/013136b9-3983-41f0-9148-308a0a4e4e2c)

2024-01-25 16:13 UTC, Kaden09 submitted a review, later dismissed
+

2024-01-28 12:47 UTC, PavelHiga commented on client/src/widgets/Sidebar/ui/Sidebar/Sidebar.tsx
>        </div>
Возможно вынести класс в отдельную переменную, чтобы код выглядел чище

2024-01-28 13:24 UTC, KirKol94 commented on client/src/widgets/Sidebar/ui/Sidebar/Sidebar.tsx
>        </div>
да в целом это норм. Это вот когда несколько условий в одном тернарнике - это звезда вообще

2024-01-28 13:52 UTC, KirKol94 requested changes
<img width="2667" alt="image" src="https://github.com/KirKol94/crm/assets/83208995/aec30d61-0215-4786-9f91-81e9e4d08c60">

а зачем столько картинок одинаковых, у свг ведь можно цвет менять

2024-01-28 13:52 UTC, KirKol94 commented on client/src/widgets/Layout/ui/Layout.tsx
> +import { Sidebar } from '@/widgets/Sidebar/Sidebar'
используй относительные пути в рамках одного слоя

2024-01-28 13:52 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +const user = { title: 'Иван Иванов', link: Avatar, to: '/' }
для путей переменная

2024-01-28 13:52 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +    to: '/users',
переменная

2024-01-28 13:52 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +    to: '/group',
и тут

2024-01-28 13:52 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +    to: '/agent',
и тут

2024-01-28 13:52 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +    to: '/contract',
и тут

2024-01-28 13:52 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +    to: '/deals',
и тут

2024-01-28 13:52 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +    to: '/setting',
и тут

2024-01-28 13:52 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +  const location = useLocation()
можно деструктуризацию сделать
```ts
const { pathname } = useLocation()
```

2024-01-28 13:52 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +  const [active, setActive] = useState<string>('')
для примитивных типов данных в хуке юзстейт совсем не обязательно дженерик типа указывать, он это сам понимает

2024-01-28 13:52 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +  const [open, setOpen] = useState(true)
булевые называй с приставкой is
ты вот типа спрашиваешь
- isOpen? 
тебе отвечают грубо говоря да / нет

```ts
const [isOpen, isActive, isAuth] = true
```

2024-01-28 13:52 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +    location.pathname === '/' && setActive(user.title)
переменная путей

2024-01-28 13:52 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +  const handleClick = () => {
тоже для читаемости было бы лучше назвать как-нибудь, чтобы было связано, например, onSidebarVisibleToggle

2024-01-28 13:52 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +    <aside className={open ? classes.sidebar : classes.sidebar__active}>
тоже как-то странно, если я правильно это понял то у тебя active, когда сайдбар закрыт. Тогда уж hidden какой-нибудь

2024-01-28 13:52 UTC, KirKol94 commented on client/src/widgets/Sidebar/SidebarItem/ui/SidebarItem.tsx
> +  }
```ts
const handeleClick = () => {
    setActive(title)
  }

useEffect(()=>{
        navigate(to)
}, [title])
```
как думаешь?

2024-01-28 13:52 UTC, KirKol94 commented on client/src/widgets/Sidebar/SidebarItem/ui/SidebarItem.tsx
> +      </li>
а тут раз навигация происходит, может быть тогда заюзать компонент Link? тогда от hanldeClick избавимся

2024-01-28 13:52 UTC, KirKol94 commented on client/src/widgets/Sidebar/SidebarItem/index.ts
для этого компонента не надо public api, мы же его юзаем только в рамках sidebar, а не отдаём выше

2024-01-28 16:55 UTC, KirKol94 requested changes
импорты поправь и всё вроде. А ещё. Почему NavLink, а не Link заюзал?

2024-01-28 16:55 UTC, KirKol94 commented on client/src/widgets/Layout/ui/Layout.tsx
> +import { Sidebar } from '../../../widgets/Sidebar/Sidebar'
```ts
import { Footer } from '../../Footer'
import { Sidebar } from '../../Sidebar/'
```

2024-01-28 16:55 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.module.scss
> +  &__hiden {
О, я вспомнил слово максимально подходящее - collapsed. Но это уже просто на будущее, тут уж можешь забить. hidden тоже понятно о чём речь

2024-01-28 16:55 UTC, KirKol94 commented on client/src/widgets/Sidebar/Sidebar/ui/Sidebar.tsx
> +import { SidebarItem } from '../../SidebarItem/ui/SidebarItem'
осознал. приношу свои извинения. просто сам ещё не сталкивался с таким, что в одном компоненте по факту два. В итоге ты был прав. Паблик апи в таком случае тоже надо

2024-01-28 17:32 UTC, KirKol94 approved these changes

2024-01-28 17:36 UTC, KirKol94 approved these changes

2024-01-28 17:49 UTC, KirKol94 approved these changes
Все 👌 вроде

2024-01-28 17:52 UTC, KirKol94 approved these changes
потрясающе

2024-01-28 18:28 UTC, KirKol94 approved these changes

2024-01-28 18:29 UTC, merged