Fe fix routing
KirKol94/crm pull request #37
Opened 2024-01-28 01:41 UTC by Ak1ro666

1)Переписал роутинг, сделал приватный роутинг для авторизированного пользователя.
2)В каком-то компоненте была папка mode, исправил на model.
3)В userSlice в setUser, деструктурировал payload(так красивее))

2024-01-28 14:10 UTC, Ak1ro666 commented on client/src/app/routes/ui/RouteSuspenseLayout.tsx
> +  return <Suspense fallback={<Loader />}>{React.cloneElement(children as React.ReactElement, { type })}</Suspense>
Да но по другому никак проблема с ленивой подгрузкой и архитектурой которую вы изначально выстроили, так как вы сделали так чтобы у вас роутинг был обёрткой а не полностью самостоятельным компонентом, сложно что-то делать, но если немного почитать, то тут нет чего-либо сложного или жуткого, просто это необычно выглядит

2024-01-28 14:11 UTC, Ak1ro666 commented on client/src/app/routes/ui/Router.tsx
> +                  {route.component && React.createElement(route.component)}
аналогично с тем что писал выше, он не работает тогда из-за ленивой подгрузки, можно было бы спокойно всё сделать будь у нас просто роуты, но с ленивой всё не так просто

2024-01-28 16:07 UTC, KirKol94 requested changes

2024-01-28 16:07 UTC, KirKol94 commented on client/src/features/AuthForm/ui/AuthForm.tsx
> +  type?: AuthType | AuthType.LOGIN
Почему тут тип не обязательный? Когда от него зависит рендеринг и функции кнопки?

2024-01-28 16:07 UTC, KirKol94 commented on client/src/pages/AuthPage/ui/AuthPage.tsx
> +  type?: AuthType | AuthType.LOGIN
вот эту строчку переведи пожалуйста на русский язык)

2024-01-29 09:39 UTC, KirKol94 approved these changes

2024-01-29 09:49 UTC, PavelHiga approved these changes

2024-01-29 09:50 UTC, merged